const blogPosts = [
    {
        id: 1,
        date: "Nov 10, 2024",
        author: "Sabyasachi Mukherjee",
        title: "The Timeless Appeal of Traditional Indian Textiles",
        excerpt: "Indian textiles have stood the test of time, offering a rich history of craftsmanship and elegance...",
        image: "/api/placeholder/400/300",
        details: "Sabyasachi Mukherjee is known for his luxurious bridal wear, featuring intricate embroidery, handwoven fabrics, and heritage-inspired designs...",
        latestFashionTrends: "Traditional handloom textiles are making a strong comeback...",
        behindTheScenes: "Each piece undergoes hours of meticulous handwork by skilled artisans...",
        fashionStylingTips: "Pair a handwoven saree with a modern blouse for a fusion look...",
        diyFashionHacks: "Upcycle old sarees into trendy jackets...",
        colorFabricGuide: "Opt for Banarasi silk in jewel tones...",
        personalJourney: "Sabyasachi’s love for textiles started with visits to Kolkata’s weavers...",
        fashionHistoryCulture: "India has a centuries-old tradition of handloom weaving...",
        sustainableEthicalFashion: "Sabyasachi promotes sustainable fashion by working with rural artisans..."
    },
    {
        id: 2,
        date: "Nov 12, 2024",
        author: "Manish Malhotra",
        title: "Bollywood's Influence on Fashion Trends",
        excerpt: "From classic sarees to modern couture, Bollywood continues to set trends that inspire millions...",
        image: "/api/placeholder/400/300",
        details: "Manish Malhotra has revolutionized Bollywood fashion...",
        latestFashionTrends: "Bollywood-inspired fusion wear is gaining popularity...",
        behindTheScenes: "From hand-stitched sequins to custom fittings...",
        fashionStylingTips: "Pair a heavily embroidered lehenga skirt with a modern crop top...",
        diyFashionHacks: "Convert an old lehenga into a gown...",
        colorFabricGuide: "Velvet in deep jewel tones adds a royal touch...",
        personalJourney: "From designing Bollywood costumes to launching his own fashion empire...",
        fashionHistoryCulture: "Bollywood has influenced Indian fashion for decades...",
        sustainableEthicalFashion: "Manish is embracing sustainable practices..."
    },
    {
        id: 3,
        date: "Nov 15, 2024",
        author: "Stella McCartney",
        title: "Sustainable Fashion: The Future of the Industry",
        excerpt: "As the world shifts toward eco-conscious living, sustainable fashion is more important than ever...",
        image: "/api/placeholder/400/300",
        details: "Stella McCartney is a pioneer of sustainable and cruelty-free fashion...",
        latestFashionTrends: "Eco-friendly fabrics, biodegradable fashion, and upcycled materials...",
        behindTheScenes: "Sustainable fashion involves innovation...",
        fashionStylingTips: "Invest in versatile, high-quality pieces...",
        diyFashionHacks: "Turn old denim into stylish tote bags...",
        colorFabricGuide: "Soft neutrals like beige and olive green...",
        personalJourney: "Stella McCartney’s commitment to sustainable fashion started with her vegetarian lifestyle...",
        fashionHistoryCulture: "The slow fashion movement is inspired by centuries-old craftsmanship traditions...",
        sustainableEthicalFashion: "Stella McCartney has led the way in eco-friendly fashion..."
    },
    {
        id: 4,
        date: "Nov 18, 2024",
        author: "Coco Chanel",
        title: "Revolutionizing Women's Fashion with Timeless Elegance",
        excerpt: "From the little black dress to effortless Parisian chic, Coco Chanel transformed fashion...",
        image: "/api/placeholder/400/300",
        details: "Coco Chanel’s influence in fashion remains unparalleled...",
        latestFashionTrends: "Minimalism and structured elegance...",
        behindTheScenes: "Chanel’s ateliers continue the tradition of impeccable craftsmanship...",
        fashionStylingTips: "A classic black dress paired with pearls never goes out of style...",
        diyFashionHacks: "Transform old blazers into chic cropped jackets...",
        colorFabricGuide: "Monochrome shades like black, white, and beige...",
        personalJourney: "Coco Chanel redefined femininity with modern, comfortable designs...",
        fashionHistoryCulture: "Chanel’s designs liberated women from corsets...",
        sustainableEthicalFashion: "The brand now incorporates sustainable sourcing in its couture..."
    },
    {
        id: 5,
        date: "Nov 22, 2024",
        author: "Ralph Lauren",
        title: "American Luxury: Defining the Classic Preppy Look",
        excerpt: "Ralph Lauren shaped American fashion with polo shirts and timeless suits...",
        image: "/api/placeholder/400/300",
        details: "Ralph Lauren’s vision blends classic elegance with a modern touch...",
        latestFashionTrends: "Preppy fashion is making a strong comeback...",
        behindTheScenes: "Each Ralph Lauren piece is crafted with premium materials...",
        fashionStylingTips: "Pair a polo shirt with tailored chinos for a refined casual look...",
        diyFashionHacks: "Convert old button-down shirts into trendy crop tops...",
        colorFabricGuide: "Navy blue, camel, and crisp white define the preppy aesthetic...",
        personalJourney: "Ralph Lauren’s journey from selling ties to a global empire...",
        fashionHistoryCulture: "His brand revolutionized American sportswear...",
        sustainableEthicalFashion: "Ralph Lauren now integrates organic fabrics in many collections..."
    },
    {
        id: 6,
        date: "Nov 25, 2024",
        author: "Gianni Versace",
        title: "The Bold and the Glamorous: Versace’s Fashion Legacy",
        excerpt: "Versace is known for its bold prints, striking colors, and fearless style...",
        image: "/api/placeholder/400/300",
        details: "Gianni Versace redefined luxury fashion...",
        latestFashionTrends: "Maximalist prints and logo-heavy designs...",
        behindTheScenes: "Each piece undergoes detailed hand-finishing...",
        fashionStylingTips: "Go bold with statement patterns...",
        diyFashionHacks: "Use fabric patches to create your own Versace-inspired look...",
        colorFabricGuide: "Gold, red, and black dominate Versace aesthetics...",
        personalJourney: "Versace’s rise from a small atelier to a global empire...",
        fashionHistoryCulture: "His designs shaped the ‘90s supermodel era...",
        sustainableEthicalFashion: "The brand is working towards cruelty-free alternatives..."
    },
    {
        id: 7,
        date: "Nov 28, 2024",
        author: "Alexander McQueen",
        title: "Fashion as Art: The Legacy of Alexander McQueen",
        excerpt: "McQueen’s avant-garde designs blurred the line between fashion and art...",
        image: "/api/placeholder/400/300",
        details: "Alexander McQueen was a visionary known for his theatrical designs...",
        latestFashionTrends: "High fashion meets dark romanticism...",
        behindTheScenes: "McQueen’s tailoring was influenced by Savile Row precision...",
        fashionStylingTips: "Structured silhouettes create an edgy yet sophisticated look...",
        diyFashionHacks: "Add lace appliques for a gothic touch...",
        colorFabricGuide: "Deep burgundy, black, and metallic shades...",
        personalJourney: "From a humble tailor’s apprentice to a legendary designer...",
        fashionHistoryCulture: "McQueen’s historical influences shaped modern couture...",
        sustainableEthicalFashion: "His brand now supports eco-conscious materials..."
    },
    {
        id: 8,
        date: "Dec 1, 2024",
        author: "Donatella Versace",
        title: "The Evolution of Power Dressing in High Fashion",
        excerpt: "How fashion empowers individuals through strong silhouettes and bold statements...",
        image: "/api/placeholder/400/300",
        details: "Donatella Versace took her brother’s legacy forward...",
        latestFashionTrends: "Sharp blazers, bold prints, and metallic tones...",
        behindTheScenes: "Precision tailoring is key in power dressing...",
        fashionStylingTips: "Pair a tailored blazer with sleek trousers...",
        diyFashionHacks: "Use gold accessories for an instant power boost...",
        colorFabricGuide: "Metallics, structured blacks, and deep blues...",
        personalJourney: "Donatella Versace modernized her brother’s bold aesthetics...",
        fashionHistoryCulture: "Power dressing has evolved since the 1980s...",
        sustainableEthicalFashion: "Versace is exploring vegan leather alternatives..."
    }
];

export default blogPosts;
